#!/usr/bin/env python3
"""Update durable Forge authority evidence after verified PR #250 CI."""

from pathlib import Path


def replace_once(path: str, old: str, new: str) -> None:
    p = Path(path)
    text = p.read_text(encoding="utf-8")
    count = text.count(old)
    if count != 1:
        raise RuntimeError(f"{path}: expected one anchor, found {count}: {old!r}")
    p.write_text(text.replace(old, new), encoding="utf-8")


report = "docs/ai-agent/OTS_AI_EQUIPMENT_UPGRADE_VALIDATION.md"

replace_once(report, "> **Documentation branch:** `docs/equipment-upgrade-handoff-refresh`  \n> **Documentation PR:** `#242`  ", "> **Active implementation branch:** `fix/forge-server-authority`  \n> **Active implementation PR:** `#250`  ")
replace_once(report, "> **Evidence boundary:** structural/static/semantic and compiled-regression evidence exist; full runtime, gameplay and physical-client E2E parity do not.", "> **Evidence boundary:** F-003–F-005 have semantic and compiled-regression evidence on PR #250; full Forge runtime gameplay and physical-client E2E parity do not.")
replace_once(report, "| Open Forge PRs | none found |\n| Active Forge tasks | none found in open PR/task searches or the read-only coordination snapshot |\n| Last merged Forge PR | #177, merge `f1d217c43e8e302978f533212e6aa9d1ce2b77c8` |", "| Open Forge PRs | #250 — bounded F-003–F-005 server-authority remediation |\n| Active Forge tasks | `CAN-20260713-forge-server-authority` under `CAN-PROGRAM-EQUIPMENT-UPGRADE-PARITY` |\n| Last merged Forge PR | #177, merge `f1d217c43e8e302978f533212e6aa9d1ce2b77c8`; #250 pending merge |")
replace_once(report, "| Current validation state | F-001–F-024 rechecked against current source history; no later Forge implementation PR found |", "| Current validation state | F-003–F-005 remediated and regression-tested on PR #250; all remaining finding states are unchanged |")
replace_once(report, "| Current handoff task | `docs/agents/tasks/active/CAN-20260713-equipment-upgrade-handoff-refresh.md` |\n| Current documentation PR | #242, documentation-only |", "| Current handoff task | `docs/agents/tasks/active/CAN-20260713-forge-server-authority.md` |\n| Current implementation PR | #250 |")
replace_once(report, "- `src/game/functions/forge_transfer_policy.hpp`.", "- `src/game/functions/forge_fusion_policy.hpp`;\n- `src/game/functions/forge_transfer_policy.hpp`.")
replace_once(report, "| F-003 | open | still-open | `Player::forgeFuseItems`; regular Fusion still lacks an independent identical-item-ID authority check and historical integration permits different IDs | none | crafted/stale packet regression before any mutation | first bounded server-authority PR |", "| F-003 | open | remediated-on-PR-branch; compiled-regression-passed | PR #250 adds `ForgeFusionPolicy` and rejects different item IDs in `Player::forgeFuseItems` before resource/chest/item mutation; the historical different-ID success integration test is now a no-mutation rejection test | #250 | merge to `main`; focused protocol/gameplay execution remains separate evidence | preserve in later transactional work |")
replace_once(report, "| F-004 | open | still-open | `Player::forgeFuseItems` and `ProtocolGame::sendOpenForge`; class 4, different IDs and normalized slot restrictions are not fully duplicated server-side | none | crafted Convergence packet tests for class, identity, slot and tier | same bounded authority family as F-003, not atomicity/history |", "| F-004 | open | remediated-on-PR-branch; compiled-regression-passed | PR #250 duplicates the Convergence pair contract server-side: different IDs, both class 4 and the same normalized slot; existing item lookup enforces requested tier, distinct copies and no active imbuements | #250 | merge to `main`; focused gameplay through the protocol remains pending | preserve in later bonus/protocol work |")
replace_once(report, "| F-005 | open | still-open | `Player::forgeTransferItemTier` uses matching classification/tier policy from #89 but does not additionally require class 4 for Convergence | #89 partially relevant | crafted Convergence Transfer class rejection before mutation | same bounded authority family as F-003/F-004 |", "| F-005 | open | remediated-on-PR-branch; compiled-regression-passed | PR #250 extends `ForgeTransferPolicy` so convergence requires matching class 4 while normal Transfer retains #89 donor-tier/classification behavior; integration regression proves non-class-4 rejection before mutation | #89 baseline + #250 | merge to `main`; focused gameplay execution remains pending | preserve normal Transfer policy |")
replace_once(report, "- **still-open:** F-001–F-006, F-011–F-012, F-014–F-024;\n- **runtime-untested:** F-007, F-008, F-013;\n- **target-version-decision-required:** F-009, F-010;\n- **remediated/superseded/no-longer-applicable:** none of F-001–F-024 is promoted to these final states by this refresh.", "- **remediated-on-PR-branch; compiled-regression-passed:** F-003, F-004, F-005 on #250;\n- **still-open:** F-001–F-002, F-006, F-011–F-012, F-014–F-024;\n- **runtime-untested:** F-007, F-008, F-013;\n- **target-version-decision-required:** F-009, F-010;\n- **full gameplay/E2E parity:** not claimed.")
replace_once(report, "- no later merged/open Canary PR remediates F-001–F-024;", "- PR #250 is the bounded active remediation for F-003–F-005; it does not address other findings;")
replace_once(report, "The final documentation PR's current-head workflow IDs and concrete jobs are recorded in the task/PR before merge.", "PR #250 readiness CI run `29250747788` succeeded on the implementation diff before the final evidence-only commit: Lua Tests and Fast Checks passed; Linux debug compiled, ran Canary smoke, imported the database schema and passed `Run Tests`; Linux release compiled and passed Canary/global datapack smoke; macOS compiled and passed runtime smoke; Windows CMake/runtime and MSBuild paths passed; Docker image build/validation passed. Fast Checks produced formatting commit `f50c9c73eeb5265461409d419c5daf853fc17ab4`. A fresh final-head run is still required after documentation bookkeeping; this run is compiled/runtime regression evidence, not focused real-client gameplay proof.")
replace_once(report, "1. regular Fusion accepts identical IDs and rejects crafted different IDs before mutation;\n2. Convergence Fusion/Transfer enforce class 4 and exact identity/slot/tier rules server-side;\n3. every rejected or failed operation preserves items, Dust, cores and gold;", "1. preserve PR #250 regressions: regular Fusion accepts identical IDs and rejects crafted different IDs before mutation;\n2. preserve PR #250 Convergence Fusion/Transfer class, identity, normalized-slot and tier authority; add focused protocol/gameplay execution before claiming full parity;\n3. extend no-mutation guarantees from invalid-request rejection to injected failures during valid operations in F-020/F-021;")
replace_once(report, "1. **F-003–F-005:** server-authority validation before any mutation;\n2. **F-020–F-021:** atomicity and rollback;", "1. **F-020–F-021:** atomicity and rollback after preserving #250 authority checks;")
replace_once(report, "- did not change or prepare gameplay code, tests, workflows, E2E infrastructure or OTClient;\n- no uncommitted code fragment exists because no local checkout exists;", "- created parity program `CAN-PROGRAM-EQUIPMENT-UPGRADE-PARITY`, task `CAN-20260713-forge-server-authority` and PR #250;\n- implemented localized C++ authority checks and focused unit/integration regressions for F-003–F-005;\n- used temporary controlled runner PR #252 because local GitHub DNS was unavailable; failed exact-anchor attempts changed no source, the successful run was `29250410323`, and the runner was closed unmerged;\n- removed all temporary runner files from the final PR diff;\n- completed full readiness CI run `29250747788` before this evidence update;\n- no local checkout or uncommitted local code exists;")
replace_once(report, "| Branch | `docs/equipment-upgrade-handoff-refresh` |\n| PR | #242 |\n| Task | `docs/agents/tasks/active/CAN-20260713-equipment-upgrade-handoff-refresh.md` |\n| Current status | documentation refresh in progress until PR/cleanup merge |", "| Branch | `fix/forge-server-authority` |\n| PR | #250 |\n| Program | `docs/agents/programs/EQUIPMENT_UPGRADE_PARITY_PROGRAM.md` |\n| Task | `docs/agents/tasks/active/CAN-20260713-forge-server-authority.md` |\n| Current status | F-003–F-005 implementation and compiled regressions complete; final-head CI/merge pending |")
replace_once(report, "| Changed files | this report and task record only |\n| Completed | current-main history/overlap review, F-001–F-024 classification, bounded plan, DNS record |\n| Incomplete | final PR CI/merge and post-merge task archive until recorded complete |", "| Changed files | localized Player authority, two internal policy helpers, Forge unit/integration tests, program/task/report/catalogue/changelog |\n| Completed | F-003–F-005 implementation; no-mutation regression coverage; full pre-evidence readiness CI `29250747788` |\n| Incomplete | fresh final-head CI, merge, task archive and all remaining Forge findings |")
replace_once(report, "| First bounded follow-up | F-003–F-005 server-authority validation before mutation |\n| First server file/functions | `src/creatures/players/player.cpp`: `Player::forgeFuseItems`, then `Player::forgeTransferItemTier` |", "| Next bounded follow-up | F-020–F-021 transactional mutation/rollback |\n| Next server file/functions | `src/creatures/players/player.cpp`: `Player::forgeFuseItems`, `Player::forgeTransferItemTier`, `Player::forgeResourceConversion` |")

catalog = "docs/agents/MODULE_CATALOG.md"
old_catalog = "| Forge history ID resolution | merged (#110) | Resolves history item types by ID with name fallback | Forge sources/integration test | Reuse ID-based lookup for custom/duplicate names. |"
new_catalog = old_catalog + "\n| Forge server authority policies | active (#250) | Validates regular/Convergence Fusion pairs and Transfer class/tier rules before mutation | `src/game/functions/forge_fusion_policy.hpp`, `forge_transfer_policy.hpp`, Player Forge handlers, focused unit/integration tests | Preserve normal Transfer rules from #89; runtime gameplay/E2E and transaction rollback remain separate evidence. |"
replace_once(catalog, old_catalog, new_catalog)

changelog = "docs/agents/CHANGELOG.md"
replace_once(changelog, "- Documented Canary ↔ OTClient cyclopedia protocol field ordering, compatibility policy, ownership, validation expectations and coordinated rollout rules in the cross-repository contract registry.\n", "- Documented Canary ↔ OTClient cyclopedia protocol field ordering, compatibility policy, ownership, validation expectations and coordinated rollout rules in the cross-repository contract registry.\n- Added bounded Forge server-authority policies and regressions in PR #250 so crafted normal Fusion, Convergence Fusion and Convergence Transfer requests are rejected before item/resource/history mutation; full Forge parity remains tracked by `CAN-PROGRAM-EQUIPMENT-UPGRADE-PARITY`.\n")

print("Updated Forge authority report, module catalogue and changelog evidence.")
