-- Account-wide quest system configuration.
-- This file is loaded by scripts/custom/account_quest_system.lua.
-- Restart the server after changing it.

local yalahar = Storage.Quest.U8_4.InServiceOfYalahar
local newFrontier = Storage.Quest.U8_54.TheNewFrontier
local wrath = Storage.Quest.U8_6.WrathOfTheEmperor

return {
	enabled = true,
	shareAccess = true,
	defaultRewardMode = "oncePerAccount",
	allowSelfReset = false,
	quests = {
		["the-ape-city"] = {
			rewardMode = "oncePerCharacter",
			progressStorages = {
				40612,
				40613,
				40614,
				40615,
				40616,
				40617,
				40618,
				40619,
				40620,
				40621,
				40622,
				40623,
				40624,
				40625,
				40626,
				40627,
				40628,
			},
		},
		["secret-service"] = {
			rewardMode = "oncePerCharacter",
			progressStorages = {
				41440,
				41441,
				41442,
				41443,
				41444,
				41445,
				41446,
				41447,
				41448,
				41449,
				41450,
				41451,
				41452,
				41453,
				41454,
				41455,
				41456,
				41457,
				41458,
				41459,
				41460,
				41461,
				41462,
				41463,
				41464,
				41465,
				41466,
				41467,
				41468,
				41469,
				41470,
			},
		},
		["in-service-of-yalahar"] = {
			rewardMode = "oncePerCharacter",
			progressStorages = {
				yalahar.TheWayToYalahar,
				yalahar.Questline,
				yalahar.Mission01,
				yalahar.Mission02,
				yalahar.Mission03,
				yalahar.Mission04,
				yalahar.Mission05,
				yalahar.Mission06,
				yalahar.Mission07,
				yalahar.Mission08,
				yalahar.Mission09,
				yalahar.Mission10,
				yalahar.SewerPipe01,
				yalahar.SewerPipe02,
				yalahar.SewerPipe03,
				yalahar.SewerPipe04,
				yalahar.DiseasedDan,
				yalahar.DiseasedBill,
				yalahar.DiseasedFred,
				yalahar.AlchemistFormula,
				yalahar.BadSide,
				yalahar.GoodSide,
				yalahar.MrWestDoor,
				yalahar.MrWestStatus,
				yalahar.TamerinStatus,
				yalahar.MorikSummon,
				yalahar.QuaraState,
				yalahar.QuaraSplasher,
				yalahar.QuaraSharptooth,
				yalahar.QuaraInky,
				yalahar.MatrixState,
				yalahar.SideDecision,
				yalahar.MatrixReward,
				yalahar.NotesPalimuth,
				yalahar.NotesAzerus,
				yalahar.DoorToAzerus,
				yalahar.DoorToBog,
				yalahar.DoorToLastFight,
				yalahar.DoorToMatrix,
				yalahar.DoorToQuara,
				yalahar.DoorToReward,
				yalahar.WarGolemsMachine1,
				yalahar.WarGolemsMachine2,
			},
		},
		["the-new-frontier"] = {
			rewardMode = "oncePerCharacter",
			progressStorages = {
				newFrontier.Questline,
				newFrontier.FarmineFirstTravel,
				newFrontier.Mission01,
				newFrontier.Mission02[1],
				newFrontier.Mission02.Beaver1,
				newFrontier.Mission02.Beaver2,
				newFrontier.Mission02.Beaver3,
				newFrontier.Mission03,
				newFrontier.Mission04,
				newFrontier.Mission05[1],
				newFrontier.Mission05.KingTibianus,
				newFrontier.Mission05.Leeland,
				newFrontier.Mission05.Angus,
				newFrontier.Mission05.Wyrdin,
				newFrontier.Mission05.Telas,
				newFrontier.Mission05.Humgolf,
				newFrontier.Mission05.LeelandKeyword,
				newFrontier.Mission05.AngusKeyword,
				newFrontier.Mission05.WyrdinKeyword,
				newFrontier.Mission05.TelasKeyword,
				newFrontier.Mission05.HumgolfKeyword,
				newFrontier.Mission06,
				newFrontier.Mission07[1],
				newFrontier.Mission07.HiddenNote,
				newFrontier.Mission08,
				newFrontier.Mission09[1],
				newFrontier.Mission09.ArenaDoor,
				newFrontier.Mission09.RewardDoor,
				newFrontier.Mission10[1],
				newFrontier.Mission10.MagicCarpetDoor,
			},
		},
		["wrath-of-the-emperor"] = {
			rewardMode = "oncePerCharacter",
			progressStorages = {
				wrath.Questline,
				wrath.Mission01,
				wrath.Mission02,
				wrath.Mission03,
				wrath.Mission04,
				wrath.Mission05,
				wrath.Mission06,
				wrath.Mission07,
				wrath.Mission08,
				wrath.Mission09,
				wrath.Mission10,
				wrath.Mission11,
				wrath.Mission12,
				wrath.Message,
				wrath.GuardcaughtYou,
				wrath.ZumtahStatus,
				wrath.PrisonReleaseStatus,
				wrath.GhostOfAPriest01,
				wrath.GhostOfAPriest02,
				wrath.GhostOfAPriest03,
				wrath.InterdimensionalPotion,
				wrath.BossStatus,
				wrath.TeleportAccess.Rebel,
				wrath.TeleportAccess.Zlak,
				wrath.TeleportAccess.Zizzle,
				wrath.TeleportAccess.SleepingDragon,
				wrath.TeleportAccess.InnerSanctum,
				wrath.TeleportAccess.AwarnessEmperor,
				wrath.TeleportAccess.Wote10,
				wrath.TeleportAccess.BossRoom,
				wrath.Light01,
				wrath.Light02,
				wrath.Light03,
				wrath.Light04,
				wrath.Bosses.Fury,
				wrath.Bosses.Wrath,
				wrath.Bosses.Scorn,
				wrath.Bosses.Spite,
			},
		},
	},
}
